# Generated by Django 5.2.11 on 2026-02-14 08:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.PositiveIntegerField(db_index=True, help_text='External customer ID from Excel / APIs', unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('monthly_salary', models.PositiveIntegerField(help_text='Monthly income of customer')),
                ('approved_limit', models.PositiveIntegerField(help_text='Approved credit limit based on salary')),
                ('current_debt', models.PositiveIntegerField(default=0, help_text='Total outstanding loan amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['customer_id'],
                'indexes': [models.Index(fields=['customer_id'], name='credit_cust_custome_da87b3_idx'), models.Index(fields=['phone_number'], name='credit_cust_phone_n_8d7b46_idx')],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.PositiveIntegerField(db_index=True, help_text='External loan ID from Excel / APIs', unique=True)),
                ('loan_amount', models.PositiveIntegerField(help_text='Principal loan amount')),
                ('tenure', models.PositiveIntegerField(help_text='Loan tenure in months')),
                ('interest_rate', models.FloatField(help_text='Annual interest rate (percentage)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('monthly_repayment', models.FloatField(help_text='Monthly EMI', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('emis_paid_on_time', models.PositiveIntegerField(default=0, help_text='Number of EMIs paid on time')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True, help_text='True if loan is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='credit.customer')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['loan_id'], name='credit_loan_loan_id_9cb7b6_idx'), models.Index(fields=['customer', 'is_active'], name='credit_loan_custome_24f6ea_idx')],
            },
        ),
    ]
