# Generated by Django 5.2.11 on 2026-02-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.PositiveIntegerField(db_index=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.PositiveIntegerField(db_index=True, editable=False, unique=True),
        ),
    ]
